defaults:
  - meta_base

cls:
  _target_: methods.protoformer.ProtoFormer
  n_layer: ${protoformer_layer_num}
  n_head: ${protoformer_head_num}
  contrastive_coef: ${contrastive_coef}
  n_sub_support: ${sub_support}
  ffn_dim: ${dim_feedforward}
  dropout: ${dropout}
  norm_first: ${encoder_norm_first}
  contrastive_loss: ${contrastive_loss}


name: protoformer
