defaults:
  - meta_base

cls:
  _target_: methods.protoformer.ProtoFormer
  n_layer: ${protoformer_layer_num}
  n_head: ${protoformer_head_num}
  contrastive_coef: ${contrastive_coef}
  n_sub_support: ${sub_support}
  ffn_dim: ${feedforward_dim}


name: protoformer
stop_epoch: 100