# @package _global_

defaults:
  - classification_base


dataset:
  name: swissprot_no_bacbone
  embed_dir: "embeds"
  simple_cls:
    _target_: datasets.prot.swissprot.SPSimpleDataset

  set_cls:
    _target_: datasets.prot.swissprot.SPSetDataset
    embed_dir: ${embed_dir}

backbone:
  _target_: backbones.id.Id

train_classes: 59

n_way: 5
n_shot: 5
n_query: 15